import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window
{
    title: "TerminalChess";
    width: 600px;
    height: 750px;
    background: #111111;

    in property <[string]> board_pieces;
    in property <string> log_text: "> Sistem Beklemede...";
    
    callback square_clicked(int);
    callback moveButtonClicked(int);

    VerticalBox
    {
        padding: 20px;
        spacing: 20px;
    
        // buton paneli
        HorizontalBox
        {
            height: 40px;
            Button
            {
                text: "Bot Oyna";
                clicked => { root.moveButtonClicked(1); }
            }
            Button
            {
                text: "Sıfırla";
                clicked => { root.moveButtonClicked(0); }
            }
        }

        // satnaç tahtası
        Rectangle
        {
            background: #222;
            border-color: #444;
            border-width: 5px;
            height: 480px;
            width: 480px;
            
            for piece[i] in root.board_pieces : Rectangle
            {
                width: 60px;
                height: 60px;
                
                x: mod(i, 8) * 60px;
                y: floor(i / 8) * 60px;

                background: mod(floor(i / 8) + i, 2) == 0 ? #eeeed2 : #769656;
                
                TouchArea
                {
                    clicked => { root.square_clicked(i); }
                }

                // Piece icons
                Text
                {
                    font-family: "Segoe UI Symbol";
                    text: piece;
                    color: black;
                    font-size: 40px;
                    x: 10px;
                    y: 5px;
                }
            }
        }

        // Log ekranı
        Rectangle
        {
            background: #000000;
            border-color: #00ff00;
            border-width: 1px;
            height: 120px;
            
            Text
            {
                text: root.log_text;
                color: #00ff00;
                font-family: "monospace";
                font-size: 14px;
                x: 10px;
                y: 10px;
                width: parent.width - 20px;
                wrap: word-wrap;
            }
        }
    }
}