import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window
{
    title: "FlameBot v0.9.1";
    width: 600px;
    height: 750px;
    background: #0a0a0c;

    in property <[string]> board_pieces;
    in property <string> log_text: "> SYSTEM WAITS...";
    in property <[image]> board_icons;
    
    callback square_clicked(int);
    callback moveButtonClicked(int);

    VerticalBox
    {
        padding: 20px;
        spacing: 20px;
    
        HorizontalBox
        {
            height: 40px;
            Button
            {
                text: "START ENGINE";
                clicked => { root.moveButtonClicked(1); }
            }
            Button
            {
                text: "RELOAD";
                clicked => { root.moveButtonClicked(0); }
            }
        }

        Rectangle
        {
            background: #1a1a1e;
            border-color: #fe53bb;
            border-width: 3px; 
            height: 486px;
            width: 486px; 
            
            for img[i] in root.board_icons : Rectangle
            {
                width: 60px;
                height: 60px;
                
                x: mod(i, 8) * 60px + 3px;
                y: floor(i / 8) * 60px + 3px;

                background: mod(floor(i / 8) + i, 2) == 0 ? #2a2a35 : #15151b;
                
                TouchArea
                {
                    clicked => { root.square_clicked(i); }
                }

                Image
                {
                    source: img;
                    width: 50px;
                    height: 50px;
                    x: 5px;
                    y: 5px;
                    image-fit: contain;
                }
            }
        }

        // Log ekranı
        Rectangle
        {
            background: #000000;
            border-color: #08f7fe;
            border-width: 2px;
            height: 120px;
            
            Text
            {
                text: root.log_text;
                color: #08f7fe;
                font-family: "monospace";
                font-size: 14px;
                x: 10px;
                y: 10px;
                width: parent.width - 20px;
                wrap: word-wrap;
            }
        }
    }
}